import os
from typing import List, Dict

EXCHANGE_ID     = "binanceusdm"
API_KEY         = os.getenv("BINANCE_API_KEY", "")
API_SECRET      = os.getenv("BINANCE_API_SECRET", "")
DISCORD_WEBHOOK_URL = os.getenv("DISCORD_WEBHOOK_URL", "")

WATCHLIST: List[str] = [
    "BTC/USDT:USDT",
    "ETH/USDT:USDT",
    "SOL/USDT:USDT",
    "BNB/USDT:USDT",
    "ARB/USDT:USDT",
    "DOGE/USDT:USDT",
    "XRP/USDT:USDT",
    "LINK/USDT:USDT",
    "AVAX/USDT:USDT",
    "MATIC/USDT:USDT",
    "ATOM/USDT:USDT",
    "NEAR/USDT:USDT",
    "OP/USDT:USDT",
    "SUI/USDT:USDT",
    "TIA/USDT:USDT",
]

BASKETS: Dict[str, List[str]] = {
    "SOL/USDT:USDT": ["BTC/USDT:USDT", "ETH/USDT:USDT", "BNB/USDT:USDT"],
    "ARB/USDT:USDT": ["ETH/USDT:USDT", "BTC/USDT:USDT", "BNB/USDT:USDT"],
    "BNB/USDT:USDT": ["BTC/USDT:USDT", "ETH/USDT:USDT", "SOL/USDT:USDT"],
    "ETH/USDT:USDT": ["BTC/USDT:USDT", "BNB/USDT:USDT", "SOL/USDT:USDT"],
    "BTC/USDT:USDT": ["ETH/USDT:USDT", "BNB/USDT:USDT", "SOL/USDT:USDT"],
    "DOGE/USDT:USDT": ["BTC/USDT:USDT", "ETH/USDT:USDT", "SOL/USDT:USDT"],
    "XRP/USDT:USDT": ["BTC/USDT:USDT", "ETH/USDT:USDT", "BNB/USDT:USDT"],
    "LINK/USDT:USDT": ["ETH/USDT:USDT", "BTC/USDT:USDT", "SOL/USDT:USDT"],
    "AVAX/USDT:USDT": ["BTC/USDT:USDT", "ETH/USDT:USDT", "SOL/USDT:USDT"],
    "MATIC/USDT:USDT": ["ETH/USDT:USDT", "BTC/USDT:USDT", "SOL/USDT:USDT"],
    "ATOM/USDT:USDT": ["BTC/USDT:USDT", "ETH/USDT:USDT", "SOL/USDT:USDT"],
    "NEAR/USDT:USDT": ["ETH/USDT:USDT", "BTC/USDT:USDT", "SOL/USDT:USDT"],
    "OP/USDT:USDT": ["ETH/USDT:USDT", "BTC/USDT:USDT", "ARB/USDT:USDT"],
    "SUI/USDT:USDT": ["ETH/USDT:USDT", "SOL/USDT:USDT", "BTC/USDT:USDT"],
    "TIA/USDT:USDT": ["BTC/USDT:USDT", "ETH/USDT:USDT", "SOL/USDT:USDT"],
}

MAX_SIGNALS_PER_DAY   = 8
SIGNAL_COOLDOWN_HOURS = 2

TRADING_START_HOUR    = 5
TRADING_END_HOUR      = 21

MIN_SCORE_ACTIONABLE  = 50
MIN_SCORE_SNIPER      = 80
MIN_SCORE_FALLBACK    = 35

OBI_LEVELS            = 5
OBI_TRIGGER_RATIO     = 2.5

CVD_SPIKE_THRESHOLD   = 1.8

ZSCORE_WINDOW         = 20
ZSCORE_ENTRY          = 2.2
ZSCORE_EXIT           = 0.5
ZSCORE_TIMEFRAME      = "5m"

SWEEP_TIMEFRAMES      = ["15m", "5m"]
EXECUTION_TF          = "1m"
EQL_TOLERANCE_PCT     = 0.0015
SWEEP_CONFIRM_PCT     = 0.002
MSS_LOOKBACK_BARS     = 20

FUNDING_LONG_MAX      = 0.0004
FUNDING_SHORT_MIN     = -0.0001
OI_CHANGE_THRESHOLD   = 0.015

KELLY_FRACTION        = 0.25
KELLY_MAX_RISK_PCT    = 2.0
KELLY_MIN_RISK_PCT    = 0.25
SETUP_WIN_RATES: Dict[str, float] = {
    "LIQUIDATION_SWEEP": 0.65,
    "STAT_ARB":          0.60,
    "OBI_CVD":           0.58,
    "COMPOSITE":         0.63,
    "ROTATION":          0.55,
}
SETUP_WIN_LOSS_RATIOS: Dict[str, float] = {
    "LIQUIDATION_SWEEP": 2.2,
    "STAT_ARB":          1.8,
    "OBI_CVD":           1.6,
    "COMPOSITE":         2.0,
    "ROTATION":          1.5,
}

LEVERAGE_MAP: Dict[str, int] = {
    "BTC/USDT:USDT": 10,
    "ETH/USDT:USDT": 10,
    "SOL/USDT:USDT": 7,
    "BNB/USDT:USDT": 7,
    "ARB/USDT:USDT": 5,
    "DOGE/USDT:USDT": 5,
    "XRP/USDT:USDT": 7,
    "LINK/USDT:USDT": 7,
    "AVAX/USDT:USDT": 5,
    "MATIC/USDT:USDT": 5,
    "ATOM/USDT:USDT": 5,
    "NEAR/USDT:USDT": 5,
    "OP/USDT:USDT": 5,
    "SUI/USDT:USDT": 5,
    "TIA/USDT:USDT": 5,
}

DAILY_DRAWDOWN_LIMIT  = 0.03
ACCOUNT_BALANCE_USDT  = float(os.getenv("ACCOUNT_BALANCE_USDT", "1000"))

TP_TIER_1_R           = 1.0
TP_TIER_2_R           = 2.0
TP_TIER_3_R           = 3.5

DASHBOARD_HOST        = "0.0.0.0"
DASHBOARD_PORT        = 8000

LOG_LEVEL             = os.getenv("LOG_LEVEL", "INFO")
LOG_FILE              = "logs/engine.log"
